### ISSUE TITLE
Can not reproduce the fid score of the paper

### ISSUE THREAD

**Issue by jingheya** [facebookresearch/StyleNeRF#50]
Dear authors,
Thanks for sharing this excellent work! 
I tried to train the new StyleNeRF model by running the `run_train.py` , but I could not get the fid score consistent with the original paper.
I train the model on FFHQ (resolution is 256*256) by 8 Nvidia V100 GPUs and use the configuration by default, i.e., spec=paper512, model=stylenerf_ffhq. However, I got the 10.48 FID when cur_img=017000+ which is 8.00 in the original paper. Could you tell me where I can modified to reproduce the results in the paper. 
The details of config.yaml, paper512.yaml and stylenerf_ffhq.yaml are below. 

config.yaml
```
defaults:
  - _self_
  - model: stylenerf_ffhq
  - spec: paper512

# general options
outdir: ~
dry_run: False
debug: False
resume_run: ~

snap: 50    # Snapshot interval [default: 50 ticks]
imgsnap: 200
metrics: [ "fid50k_full" ]
seed: 2
num_fp16_res: 4
auto: False

# dataset
data: ~
resolution: ~
cond: False
subset: ~   # Train with only N images: <int>, default = all
mirror: False

# discriminator augmentation
aug: noaug
p: ~
target: ~
augpipe: ~

# transfer learning
resume: ~
freezed: ~

# performance options
fp32: False
nhwc: False
allow_tf32: False
nobench: False
workers: 1

launcher: "ddp"
partition: ~
comment: ~
gpus: ~     # Number of GPUs to use [default: 1]
port: ~
nodes: ~
timeout: ~
```

paper512.yaml
```
name: paper512
ref_gpus: 8
kimg: 25000
mb: 64 # Total batch size for one training iteration. Can be larger than batch_gpu * world_size
mbstd: 8 # batch size for once GPU
fmaps: 1
lrate: 0.0025
lrate_disc: 0.0025
gamma: 0.5
ema: 20
ramp: ~
map: 8
```

stylenerf_ffhq.yaml
```
# @package _group_
name: stylenerf_ffhq

G_kwargs:
    class_name: "training.networks.Generator"
    z_dim: 512
    w_dim: 512

    mapping_kwargs:
        module_name: "training.networks.MappingNetwork"
        num_layers: ${spec.map}

    synthesis_kwargs:
        # global settings
        num_fp16_res: ${num_fp16_res}
        channel_base: 1
        channel_max: 1024
        conv_clamp: 256
        kernel_size: 1
        architecture: skip
        upsample_mode: "nn_cat"

        z_dim_bg: 32
        z_dim: 0
        resolution_vol: 32
        resolution_start: 32
        rgb_out_dim: 256

        use_noise: False
        module_name: "training.stylenerf.NeRFSynthesisNetwork"
        no_bbox: True
        margin: 0
        magnitude_ema_beta: 0.999

        camera_kwargs:
            range_v: [1.4157963267948965, 1.7257963267948966]
            range_u: [-0.3, 0.3]
            range_radius: [1.0, 1.0]
            depth_range: [0.88, 1.12]
            fov: 12
            gaussian_camera: True
            angular_camera: True
            depth_transform:  ~
            dists_normalized: False
            ray_align_corner: False
            bg_start: 0.5
        
        renderer_kwargs:
            n_bg_samples: 4
            n_ray_samples: 14
            abs_sigma: False
            hierarchical: True
            no_background: False
            
        foreground_kwargs:
            positional_encoding: "normal"
            downscale_p_by: 1
            use_style: "StyleGAN2"
            predict_rgb: True
            use_viewdirs: False

        background_kwargs:
            positional_encoding: "normal"
            hidden_size: 64
            n_blocks: 4
            downscale_p_by: 1
            skips: []
            inverse_sphere: True
            use_style: "StyleGAN2"
            predict_rgb: True
            use_viewdirs: False

        upsampler_kwargs:
            channel_base: ${model.G_kwargs.synthesis_kwargs.channel_base}
            channel_max:  ${model.G_kwargs.synthesis_kwargs.channel_max}
            no_2d_renderer: False
            no_residual_img: False
            block_reses: ~
            shared_rgb_style: False
            upsample_type: "bilinear"
        
        progressive: True

        # reuglarization
        n_reg_samples: 16
        reg_full: True

D_kwargs:
    class_name: "training.stylenerf.Discriminator"
    epilogue_kwargs:
        mbstd_group_size: ${spec.mbstd}

    num_fp16_res: ${num_fp16_res}
    channel_base: ${spec.fmaps}
    channel_max: 512
    conv_clamp: 256
    architecture: skip
    progressive: ${model.G_kwargs.synthesis_kwargs.progressive}
    lowres_head: ${model.G_kwargs.synthesis_kwargs.resolution_start}
    upsample_type: "bilinear"
    resize_real_early: True

# loss kwargs
loss_kwargs:
    pl_batch_shrink: 2
    pl_decay: 0.01
    pl_weight: 2
    style_mixing_prob: 0.9
    curriculum: [500,5000]
```
